# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: auth.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'auth.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nauth.proto\x12\x04\x61uth\"N\n\x11\x43reereContRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\x12\x18\n\x04role\x18\x03 \x01(\x0e\x32\n.auth.Role\"+\n\x12\x43reereContResponse\x12\x15\n\rrefresh_token\x18\x01 \x01(\t\"7\n\x14\x43reereSesiuneRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\".\n\x15\x43reereSesiuneResponse\x12\x15\n\rrefresh_token\x18\x01 \x01(\t\",\n\x13VerifSesiuneRequest\x12\x15\n\rrefresh_token\x18\x01 \x01(\t\"?\n\x14VerifSesiuneResponse\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x18\n\x04role\x18\x02 \x01(\x0e\x32\n.auth.Role*;\n\x04Role\x12\x0e\n\nROLE_ADMIN\x10\x00\x12\x10\n\x0cROLE_STUDENT\x10\x01\x12\x11\n\rROLE_PROFESOR\x10\x02\x32\xdf\x01\n\x0b\x41uthService\x12?\n\nCreereCont\x12\x17.auth.CreereContRequest\x1a\x18.auth.CreereContResponse\x12H\n\rCreereSesiune\x12\x1a.auth.CreereSesiuneRequest\x1a\x1b.auth.CreereSesiuneResponse\x12\x45\n\x0cVerifSesiune\x12\x19.auth.VerifSesiuneRequest\x1a\x1a.auth.VerifSesiuneResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'auth_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ROLE']._serialized_start=361
  _globals['_ROLE']._serialized_end=420
  _globals['_CREERECONTREQUEST']._serialized_start=20
  _globals['_CREERECONTREQUEST']._serialized_end=98
  _globals['_CREERECONTRESPONSE']._serialized_start=100
  _globals['_CREERECONTRESPONSE']._serialized_end=143
  _globals['_CREERESESIUNEREQUEST']._serialized_start=145
  _globals['_CREERESESIUNEREQUEST']._serialized_end=200
  _globals['_CREERESESIUNERESPONSE']._serialized_start=202
  _globals['_CREERESESIUNERESPONSE']._serialized_end=248
  _globals['_VERIFSESIUNEREQUEST']._serialized_start=250
  _globals['_VERIFSESIUNEREQUEST']._serialized_end=294
  _globals['_VERIFSESIUNERESPONSE']._serialized_start=296
  _globals['_VERIFSESIUNERESPONSE']._serialized_end=359
  _globals['_AUTHSERVICE']._serialized_start=423
  _globals['_AUTHSERVICE']._serialized_end=646
# @@protoc_insertion_point(module_scope)
